incoming_wave_height:
  description: Height of incoming waves
  value:
    default: 2.0
    range:
      max: 100.0
      min: 0.0
    type: float
    units: m
incoming_wave_period:
  description: Period of incoming waves
  value:
    default: 7.0
    range:
      max: 100.0
      min: 0.0
    type: float
    units: s
angle_highness_factor:
  description: Highness factor for incoming wave angles
  value:
    default: 0.2
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"
angle_asymmetry:
  description: Asymmetry of incoming wave angles
  value:
    default: 0.5
    range:
      max: 1.0
      min: 0.0
    type: float
    units: "-"
