number_of_rows:
  description: Number of rows in the computational grid
  value:
    default: 50
    range:
      max: 2147483647
      min: 30
    type: int
    units: "-"
number_of_cols:
  description: Number of columns in the computational grid
  value:
    default: 1000
    range:
      max: 2147483647
      min: 30
    type: int
    units: "-"
grid_spacing:
  description: Grid resolution in cross and along-shore direction
  value:
    default: 1000
    range:
      max: 1.79769e308
      min: 1.0
    type: float
    units: m
shoreface_slope:
  description: Gradient of the shoreface
  value:
    default: 0.01
    range:
      max: 1.0
      min: 0.001
    type: float
    units: m/m
shoreface_depth:
  description: Water depth of the shoreface
  value:
    default: 10.0
    range:
      max: 100.0
      min: 0.0
    type: float
    units: m
shelf_slope:
  description: Gradient of the shelf
  value:
    default: 0.001
    range:
      max: 100.0
      min: 0.0001
    type: float
    units: m/m
sediment_flux_flag:
  description: Sediment flux flag
  value:
    type: choice
    default: 1
    choices:
      - 0
      - 1
